version: 2.0
jobs:
  build_and_test:
    working_directory: ~/sample
    machine: true
    steps:
      - checkout
      - run:
          name: check docker version
          command: |
            docker version
            docker-compose version
      - run:
          name: build docker
          command: |
            docker-compose build
      - run:
          name: test
          command: |
            make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
